<?php
/**
 * Default country and state seed data used by the
 * "Restore Default Countries" admin action.
 *
 * Extracted from ec_db_manager::install_base_data() so the restore
 * action and the fresh-install seed stay in sync. If install_base_data()
 * is ever updated with new defaults, re-run extract_defaults.py to
 * regenerate this file.
 *
 * States reference their country via iso2_cnt (not the hard-coded id_cnt
 * from install_base_data) so that restores still work correctly on sites
 * where a country was previously deleted and later re-added with a new
 * auto-increment id.
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

return array(
	'countries' => array(
		array(
			'name_cnt'   => 'Afghanistan',
			'iso2_cnt'   => 'AF',
			'iso3_cnt'   => 'AFG',
			'sort_order' => 10,
		),
		array(
			'name_cnt'   => 'Albania',
			'iso2_cnt'   => 'AL',
			'iso3_cnt'   => 'ALB',
			'sort_order' => 11,
		),
		array(
			'name_cnt'   => 'Algeria',
			'iso2_cnt'   => 'DZ',
			'iso3_cnt'   => 'DZA',
			'sort_order' => 12,
		),
		array(
			'name_cnt'   => 'American Samoa',
			'iso2_cnt'   => 'AS',
			'iso3_cnt'   => 'ASM',
			'sort_order' => 13,
		),
		array(
			'name_cnt'   => 'Andorra',
			'iso2_cnt'   => 'AD',
			'iso3_cnt'   => 'AND',
			'sort_order' => 14,
		),
		array(
			'name_cnt'   => 'Angola',
			'iso2_cnt'   => 'AO',
			'iso3_cnt'   => 'AGO',
			'sort_order' => 15,
		),
		array(
			'name_cnt'   => 'Anguilla',
			'iso2_cnt'   => 'AI',
			'iso3_cnt'   => 'AIA',
			'sort_order' => 16,
		),
		array(
			'name_cnt'   => 'Antarctica',
			'iso2_cnt'   => 'AQ',
			'iso3_cnt'   => 'ATA',
			'sort_order' => 17,
		),
		array(
			'name_cnt'   => 'Antigua and Barbuda',
			'iso2_cnt'   => 'AG',
			'iso3_cnt'   => 'ATG',
			'sort_order' => 18,
		),
		array(
			'name_cnt'   => 'Argentina',
			'iso2_cnt'   => 'AR',
			'iso3_cnt'   => 'ARG',
			'sort_order' => 19,
		),
		array(
			'name_cnt'   => 'Armenia',
			'iso2_cnt'   => 'AM',
			'iso3_cnt'   => 'ARM',
			'sort_order' => 20,
		),
		array(
			'name_cnt'   => 'Aruba',
			'iso2_cnt'   => 'AW',
			'iso3_cnt'   => 'ABW',
			'sort_order' => 21,
		),
		array(
			'name_cnt'   => 'Australia',
			'iso2_cnt'   => 'AU',
			'iso3_cnt'   => 'AUS',
			'sort_order' => 3,
		),
		array(
			'name_cnt'   => 'Austria',
			'iso2_cnt'   => 'AT',
			'iso3_cnt'   => 'AUT',
			'sort_order' => 23,
		),
		array(
			'name_cnt'   => 'Azerbaijan',
			'iso2_cnt'   => 'AZ',
			'iso3_cnt'   => 'AZE',
			'sort_order' => 24,
		),
		array(
			'name_cnt'   => 'Bahamas',
			'iso2_cnt'   => 'BS',
			'iso3_cnt'   => 'BHS',
			'sort_order' => 25,
		),
		array(
			'name_cnt'   => 'Bahrain',
			'iso2_cnt'   => 'BH',
			'iso3_cnt'   => 'BHR',
			'sort_order' => 26,
		),
		array(
			'name_cnt'   => 'Bangladesh',
			'iso2_cnt'   => 'BD',
			'iso3_cnt'   => 'BGD',
			'sort_order' => 27,
		),
		array(
			'name_cnt'   => 'Barbados',
			'iso2_cnt'   => 'BB',
			'iso3_cnt'   => 'BRB',
			'sort_order' => 28,
		),
		array(
			'name_cnt'   => 'Belarus',
			'iso2_cnt'   => 'BY',
			'iso3_cnt'   => 'BLR',
			'sort_order' => 29,
		),
		array(
			'name_cnt'   => 'Belgium',
			'iso2_cnt'   => 'BE',
			'iso3_cnt'   => 'BEL',
			'sort_order' => 30,
		),
		array(
			'name_cnt'   => 'Belize',
			'iso2_cnt'   => 'BZ',
			'iso3_cnt'   => 'BLZ',
			'sort_order' => 31,
		),
		array(
			'name_cnt'   => 'Benin',
			'iso2_cnt'   => 'BJ',
			'iso3_cnt'   => 'BEN',
			'sort_order' => 32,
		),
		array(
			'name_cnt'   => 'Bermuda',
			'iso2_cnt'   => 'BM',
			'iso3_cnt'   => 'BMU',
			'sort_order' => 33,
		),
		array(
			'name_cnt'   => 'Bhutan',
			'iso2_cnt'   => 'BT',
			'iso3_cnt'   => 'BTN',
			'sort_order' => 34,
		),
		array(
			'name_cnt'   => 'Bolivia',
			'iso2_cnt'   => 'BO',
			'iso3_cnt'   => 'BOL',
			'sort_order' => 35,
		),
		array(
			'name_cnt'   => 'Botswana',
			'iso2_cnt'   => 'BW',
			'iso3_cnt'   => 'BWA',
			'sort_order' => 36,
		),
		array(
			'name_cnt'   => 'Bouvet Island',
			'iso2_cnt'   => 'BV',
			'iso3_cnt'   => 'BVT',
			'sort_order' => 37,
		),
		array(
			'name_cnt'   => 'Brazil',
			'iso2_cnt'   => 'BR',
			'iso3_cnt'   => 'BRA',
			'sort_order' => 38,
		),
		array(
			'name_cnt'   => 'Brunei Darussalam',
			'iso2_cnt'   => 'BN',
			'iso3_cnt'   => 'BRN',
			'sort_order' => 39,
		),
		array(
			'name_cnt'   => 'Bulgaria',
			'iso2_cnt'   => 'BG',
			'iso3_cnt'   => 'BGR',
			'sort_order' => 40,
		),
		array(
			'name_cnt'   => 'Burkina Faso',
			'iso2_cnt'   => 'BF',
			'iso3_cnt'   => 'BFA',
			'sort_order' => 41,
		),
		array(
			'name_cnt'   => 'Burundi',
			'iso2_cnt'   => 'BI',
			'iso3_cnt'   => 'BDI',
			'sort_order' => 42,
		),
		array(
			'name_cnt'   => 'Cambodia',
			'iso2_cnt'   => 'KH',
			'iso3_cnt'   => 'KHM',
			'sort_order' => 43,
		),
		array(
			'name_cnt'   => 'Cameroon',
			'iso2_cnt'   => 'CM',
			'iso3_cnt'   => 'CMR',
			'sort_order' => 44,
		),
		array(
			'name_cnt'   => 'Canada',
			'iso2_cnt'   => 'CA',
			'iso3_cnt'   => 'CAN',
			'sort_order' => 2,
		),
		array(
			'name_cnt'   => 'Cape Verde',
			'iso2_cnt'   => 'CV',
			'iso3_cnt'   => 'CPV',
			'sort_order' => 46,
		),
		array(
			'name_cnt'   => 'Cayman Islands',
			'iso2_cnt'   => 'KY',
			'iso3_cnt'   => 'CYM',
			'sort_order' => 47,
		),
		array(
			'name_cnt'   => 'Chad',
			'iso2_cnt'   => 'TD',
			'iso3_cnt'   => 'TCD',
			'sort_order' => 48,
		),
		array(
			'name_cnt'   => 'Chile',
			'iso2_cnt'   => 'CL',
			'iso3_cnt'   => 'CHL',
			'sort_order' => 49,
		),
		array(
			'name_cnt'   => 'China',
			'iso2_cnt'   => 'CN',
			'iso3_cnt'   => 'CHN',
			'sort_order' => 50,
		),
		array(
			'name_cnt'   => 'Christmas Island',
			'iso2_cnt'   => 'CX',
			'iso3_cnt'   => 'CXR',
			'sort_order' => 51,
		),
		array(
			'name_cnt'   => 'Colombia',
			'iso2_cnt'   => 'CO',
			'iso3_cnt'   => 'COL',
			'sort_order' => 52,
		),
		array(
			'name_cnt'   => 'Comoros',
			'iso2_cnt'   => 'KM',
			'iso3_cnt'   => 'COM',
			'sort_order' => 53,
		),
		array(
			'name_cnt'   => 'Congo',
			'iso2_cnt'   => 'CG',
			'iso3_cnt'   => 'COG',
			'sort_order' => 54,
		),
		array(
			'name_cnt'   => 'Cook Islands',
			'iso2_cnt'   => 'CK',
			'iso3_cnt'   => 'COK',
			'sort_order' => 55,
		),
		array(
			'name_cnt'   => 'Costa Rica',
			'iso2_cnt'   => 'CR',
			'iso3_cnt'   => 'CRI',
			'sort_order' => 56,
		),
		array(
			'name_cnt'   => 'Cote D\'\'Ivoire',
			'iso2_cnt'   => 'CI',
			'iso3_cnt'   => 'CIV',
			'sort_order' => 57,
		),
		array(
			'name_cnt'   => 'Croatia',
			'iso2_cnt'   => 'HR',
			'iso3_cnt'   => 'HRV',
			'sort_order' => 58,
		),
		array(
			'name_cnt'   => 'Cuba',
			'iso2_cnt'   => 'CU',
			'iso3_cnt'   => 'CUB',
			'sort_order' => 59,
		),
		array(
			'name_cnt'   => 'Cyprus',
			'iso2_cnt'   => 'CY',
			'iso3_cnt'   => 'CYP',
			'sort_order' => 60,
		),
		array(
			'name_cnt'   => 'Czech Republic',
			'iso2_cnt'   => 'CZ',
			'iso3_cnt'   => 'CZE',
			'sort_order' => 61,
		),
		array(
			'name_cnt'   => 'Denmark',
			'iso2_cnt'   => 'DK',
			'iso3_cnt'   => 'DNK',
			'sort_order' => 62,
		),
		array(
			'name_cnt'   => 'Djibouti',
			'iso2_cnt'   => 'DJ',
			'iso3_cnt'   => 'DJI',
			'sort_order' => 63,
		),
		array(
			'name_cnt'   => 'Dominica',
			'iso2_cnt'   => 'DM',
			'iso3_cnt'   => 'DMA',
			'sort_order' => 64,
		),
		array(
			'name_cnt'   => 'Dominican Republic',
			'iso2_cnt'   => 'DO',
			'iso3_cnt'   => 'DOM',
			'sort_order' => 65,
		),
		array(
			'name_cnt'   => 'East Timor',
			'iso2_cnt'   => 'TP',
			'iso3_cnt'   => 'TMP',
			'sort_order' => 66,
		),
		array(
			'name_cnt'   => 'Ecuador',
			'iso2_cnt'   => 'EC',
			'iso3_cnt'   => 'ECU',
			'sort_order' => 67,
		),
		array(
			'name_cnt'   => 'Egypt',
			'iso2_cnt'   => 'EG',
			'iso3_cnt'   => 'EGY',
			'sort_order' => 68,
		),
		array(
			'name_cnt'   => 'El Salvador',
			'iso2_cnt'   => 'SV',
			'iso3_cnt'   => 'SLV',
			'sort_order' => 69,
		),
		array(
			'name_cnt'   => 'Equatorial Guinea',
			'iso2_cnt'   => 'GQ',
			'iso3_cnt'   => 'GNQ',
			'sort_order' => 70,
		),
		array(
			'name_cnt'   => 'Eritrea',
			'iso2_cnt'   => 'ER',
			'iso3_cnt'   => 'ERI',
			'sort_order' => 71,
		),
		array(
			'name_cnt'   => 'Estonia',
			'iso2_cnt'   => 'EE',
			'iso3_cnt'   => 'EST',
			'sort_order' => 72,
		),
		array(
			'name_cnt'   => 'Ethiopia',
			'iso2_cnt'   => 'ET',
			'iso3_cnt'   => 'ETH',
			'sort_order' => 73,
		),
		array(
			'name_cnt'   => 'Faroe Islands',
			'iso2_cnt'   => 'FO',
			'iso3_cnt'   => 'FRO',
			'sort_order' => 74,
		),
		array(
			'name_cnt'   => 'Fiji',
			'iso2_cnt'   => 'FJ',
			'iso3_cnt'   => 'FJI',
			'sort_order' => 75,
		),
		array(
			'name_cnt'   => 'Finland',
			'iso2_cnt'   => 'FI',
			'iso3_cnt'   => 'FIN',
			'sort_order' => 76,
		),
		array(
			'name_cnt'   => 'France',
			'iso2_cnt'   => 'FR',
			'iso3_cnt'   => 'FRA',
			'sort_order' => 77,
		),
		array(
			'name_cnt'   => 'France, Metropolitan',
			'iso2_cnt'   => 'FX',
			'iso3_cnt'   => 'FXX',
			'sort_order' => 78,
		),
		array(
			'name_cnt'   => 'French Guiana',
			'iso2_cnt'   => 'GF',
			'iso3_cnt'   => 'GUF',
			'sort_order' => 79,
		),
		array(
			'name_cnt'   => 'French Polynesia',
			'iso2_cnt'   => 'PF',
			'iso3_cnt'   => 'PYF',
			'sort_order' => 80,
		),
		array(
			'name_cnt'   => 'Gabon',
			'iso2_cnt'   => 'GA',
			'iso3_cnt'   => 'GAB',
			'sort_order' => 81,
		),
		array(
			'name_cnt'   => 'Gambia',
			'iso2_cnt'   => 'GM',
			'iso3_cnt'   => 'GMB',
			'sort_order' => 82,
		),
		array(
			'name_cnt'   => 'Georgia',
			'iso2_cnt'   => 'GE',
			'iso3_cnt'   => 'GEO',
			'sort_order' => 83,
		),
		array(
			'name_cnt'   => 'Germany',
			'iso2_cnt'   => 'DE',
			'iso3_cnt'   => 'DEU',
			'sort_order' => 84,
		),
		array(
			'name_cnt'   => 'Ghana',
			'iso2_cnt'   => 'GH',
			'iso3_cnt'   => 'GHA',
			'sort_order' => 85,
		),
		array(
			'name_cnt'   => 'Gibraltar',
			'iso2_cnt'   => 'GI',
			'iso3_cnt'   => 'GIB',
			'sort_order' => 86,
		),
		array(
			'name_cnt'   => 'Greece',
			'iso2_cnt'   => 'GR',
			'iso3_cnt'   => 'GRC',
			'sort_order' => 87,
		),
		array(
			'name_cnt'   => 'Greenland',
			'iso2_cnt'   => 'GL',
			'iso3_cnt'   => 'GRL',
			'sort_order' => 88,
		),
		array(
			'name_cnt'   => 'Grenada',
			'iso2_cnt'   => 'GD',
			'iso3_cnt'   => 'GRD',
			'sort_order' => 89,
		),
		array(
			'name_cnt'   => 'Guadeloupe',
			'iso2_cnt'   => 'GP',
			'iso3_cnt'   => 'GLP',
			'sort_order' => 90,
		),
		array(
			'name_cnt'   => 'Guam',
			'iso2_cnt'   => 'GU',
			'iso3_cnt'   => 'GUM',
			'sort_order' => 91,
		),
		array(
			'name_cnt'   => 'Guatemala',
			'iso2_cnt'   => 'GT',
			'iso3_cnt'   => 'GTM',
			'sort_order' => 92,
		),
		array(
			'name_cnt'   => 'Guinea',
			'iso2_cnt'   => 'GN',
			'iso3_cnt'   => 'GIN',
			'sort_order' => 93,
		),
		array(
			'name_cnt'   => 'Guinea-bissau',
			'iso2_cnt'   => 'GW',
			'iso3_cnt'   => 'GNB',
			'sort_order' => 94,
		),
		array(
			'name_cnt'   => 'Guyana',
			'iso2_cnt'   => 'GY',
			'iso3_cnt'   => 'GUY',
			'sort_order' => 95,
		),
		array(
			'name_cnt'   => 'Haiti',
			'iso2_cnt'   => 'HT',
			'iso3_cnt'   => 'HTI',
			'sort_order' => 96,
		),
		array(
			'name_cnt'   => 'Honduras',
			'iso2_cnt'   => 'HN',
			'iso3_cnt'   => 'HND',
			'sort_order' => 97,
		),
		array(
			'name_cnt'   => 'Hong Kong',
			'iso2_cnt'   => 'HK',
			'iso3_cnt'   => 'HKG',
			'sort_order' => 98,
		),
		array(
			'name_cnt'   => 'Hungary',
			'iso2_cnt'   => 'HU',
			'iso3_cnt'   => 'HUN',
			'sort_order' => 99,
		),
		array(
			'name_cnt'   => 'Iceland',
			'iso2_cnt'   => 'IS',
			'iso3_cnt'   => 'ISL',
			'sort_order' => 100,
		),
		array(
			'name_cnt'   => 'India',
			'iso2_cnt'   => 'IN',
			'iso3_cnt'   => 'IND',
			'sort_order' => 101,
		),
		array(
			'name_cnt'   => 'Indonesia',
			'iso2_cnt'   => 'ID',
			'iso3_cnt'   => 'IDN',
			'sort_order' => 102,
		),
		array(
			'name_cnt'   => 'Iraq',
			'iso2_cnt'   => 'IQ',
			'iso3_cnt'   => 'IRQ',
			'sort_order' => 103,
		),
		array(
			'name_cnt'   => 'Ireland',
			'iso2_cnt'   => 'IE',
			'iso3_cnt'   => 'IRL',
			'sort_order' => 104,
		),
		array(
			'name_cnt'   => 'Israel',
			'iso2_cnt'   => 'IL',
			'iso3_cnt'   => 'ISR',
			'sort_order' => 105,
		),
		array(
			'name_cnt'   => 'Italy',
			'iso2_cnt'   => 'IT',
			'iso3_cnt'   => 'ITA',
			'sort_order' => 106,
		),
		array(
			'name_cnt'   => 'Jamaica',
			'iso2_cnt'   => 'JM',
			'iso3_cnt'   => 'JAM',
			'sort_order' => 107,
		),
		array(
			'name_cnt'   => 'Japan',
			'iso2_cnt'   => 'JP',
			'iso3_cnt'   => 'JPN',
			'sort_order' => 108,
		),
		array(
			'name_cnt'   => 'Jordan',
			'iso2_cnt'   => 'JO',
			'iso3_cnt'   => 'JOR',
			'sort_order' => 109,
		),
		array(
			'name_cnt'   => 'Kazakhstan',
			'iso2_cnt'   => 'KZ',
			'iso3_cnt'   => 'KAZ',
			'sort_order' => 110,
		),
		array(
			'name_cnt'   => 'Kenya',
			'iso2_cnt'   => 'KE',
			'iso3_cnt'   => 'KEN',
			'sort_order' => 111,
		),
		array(
			'name_cnt'   => 'Kiribati',
			'iso2_cnt'   => 'KI',
			'iso3_cnt'   => 'KIR',
			'sort_order' => 112,
		),
		array(
			'name_cnt'   => 'Korea, Republic of',
			'iso2_cnt'   => 'KR',
			'iso3_cnt'   => 'KOR',
			'sort_order' => 113,
		),
		array(
			'name_cnt'   => 'Kuwait',
			'iso2_cnt'   => 'KW',
			'iso3_cnt'   => 'KWT',
			'sort_order' => 114,
		),
		array(
			'name_cnt'   => 'Kyrgyzstan',
			'iso2_cnt'   => 'KG',
			'iso3_cnt'   => 'KGZ',
			'sort_order' => 115,
		),
		array(
			'name_cnt'   => 'Latvia',
			'iso2_cnt'   => 'LV',
			'iso3_cnt'   => 'LVA',
			'sort_order' => 116,
		),
		array(
			'name_cnt'   => 'Lebanon',
			'iso2_cnt'   => 'LB',
			'iso3_cnt'   => 'LBN',
			'sort_order' => 117,
		),
		array(
			'name_cnt'   => 'Lesotho',
			'iso2_cnt'   => 'LS',
			'iso3_cnt'   => 'LSO',
			'sort_order' => 118,
		),
		array(
			'name_cnt'   => 'Liberia',
			'iso2_cnt'   => 'LR',
			'iso3_cnt'   => 'LBR',
			'sort_order' => 119,
		),
		array(
			'name_cnt'   => 'Liechtenstein',
			'iso2_cnt'   => 'LI',
			'iso3_cnt'   => 'LIE',
			'sort_order' => 120,
		),
		array(
			'name_cnt'   => 'Lithuania',
			'iso2_cnt'   => 'LT',
			'iso3_cnt'   => 'LTU',
			'sort_order' => 121,
		),
		array(
			'name_cnt'   => 'Luxembourg',
			'iso2_cnt'   => 'LU',
			'iso3_cnt'   => 'LUX',
			'sort_order' => 122,
		),
		array(
			'name_cnt'   => 'Macau',
			'iso2_cnt'   => 'MO',
			'iso3_cnt'   => 'MAC',
			'sort_order' => 123,
		),
		array(
			'name_cnt'   => 'Madagascar',
			'iso2_cnt'   => 'MG',
			'iso3_cnt'   => 'MDG',
			'sort_order' => 124,
		),
		array(
			'name_cnt'   => 'Malawi',
			'iso2_cnt'   => 'MW',
			'iso3_cnt'   => 'MWI',
			'sort_order' => 125,
		),
		array(
			'name_cnt'   => 'Malaysia',
			'iso2_cnt'   => 'MY',
			'iso3_cnt'   => 'MYS',
			'sort_order' => 126,
		),
		array(
			'name_cnt'   => 'Maldives',
			'iso2_cnt'   => 'MV',
			'iso3_cnt'   => 'MDV',
			'sort_order' => 127,
		),
		array(
			'name_cnt'   => 'Mali',
			'iso2_cnt'   => 'ML',
			'iso3_cnt'   => 'MLI',
			'sort_order' => 128,
		),
		array(
			'name_cnt'   => 'Malta',
			'iso2_cnt'   => 'MT',
			'iso3_cnt'   => 'MLT',
			'sort_order' => 129,
		),
		array(
			'name_cnt'   => 'Marshall Islands',
			'iso2_cnt'   => 'MH',
			'iso3_cnt'   => 'MHL',
			'sort_order' => 130,
		),
		array(
			'name_cnt'   => 'Martinique',
			'iso2_cnt'   => 'MQ',
			'iso3_cnt'   => 'MTQ',
			'sort_order' => 131,
		),
		array(
			'name_cnt'   => 'Mauritania',
			'iso2_cnt'   => 'MR',
			'iso3_cnt'   => 'MRT',
			'sort_order' => 132,
		),
		array(
			'name_cnt'   => 'Mauritius',
			'iso2_cnt'   => 'MU',
			'iso3_cnt'   => 'MUS',
			'sort_order' => 133,
		),
		array(
			'name_cnt'   => 'Mayotte',
			'iso2_cnt'   => 'YT',
			'iso3_cnt'   => 'MYT',
			'sort_order' => 134,
		),
		array(
			'name_cnt'   => 'Mexico',
			'iso2_cnt'   => 'MX',
			'iso3_cnt'   => 'MEX',
			'sort_order' => 135,
		),
		array(
			'name_cnt'   => 'Monaco',
			'iso2_cnt'   => 'MC',
			'iso3_cnt'   => 'MCO',
			'sort_order' => 136,
		),
		array(
			'name_cnt'   => 'Mongolia',
			'iso2_cnt'   => 'MN',
			'iso3_cnt'   => 'MNG',
			'sort_order' => 137,
		),
		array(
			'name_cnt'   => 'Montserrat',
			'iso2_cnt'   => 'MS',
			'iso3_cnt'   => 'MSR',
			'sort_order' => 138,
		),
		array(
			'name_cnt'   => 'Morocco',
			'iso2_cnt'   => 'MA',
			'iso3_cnt'   => 'MAR',
			'sort_order' => 139,
		),
		array(
			'name_cnt'   => 'Mozambique',
			'iso2_cnt'   => 'MZ',
			'iso3_cnt'   => 'MOZ',
			'sort_order' => 140,
		),
		array(
			'name_cnt'   => 'Myanmar',
			'iso2_cnt'   => 'MM',
			'iso3_cnt'   => 'MMR',
			'sort_order' => 141,
		),
		array(
			'name_cnt'   => 'Namibia',
			'iso2_cnt'   => 'NA',
			'iso3_cnt'   => 'NAM',
			'sort_order' => 142,
		),
		array(
			'name_cnt'   => 'Nauru',
			'iso2_cnt'   => 'NR',
			'iso3_cnt'   => 'NRU',
			'sort_order' => 143,
		),
		array(
			'name_cnt'   => 'Nepal',
			'iso2_cnt'   => 'NP',
			'iso3_cnt'   => 'NPL',
			'sort_order' => 144,
		),
		array(
			'name_cnt'   => 'Netherlands',
			'iso2_cnt'   => 'NL',
			'iso3_cnt'   => 'NLD',
			'sort_order' => 145,
		),
		array(
			'name_cnt'   => 'Netherlands Antilles',
			'iso2_cnt'   => 'AN',
			'iso3_cnt'   => 'ANT',
			'sort_order' => 146,
		),
		array(
			'name_cnt'   => 'New Caledonia',
			'iso2_cnt'   => 'NC',
			'iso3_cnt'   => 'NCL',
			'sort_order' => 147,
		),
		array(
			'name_cnt'   => 'New Zealand',
			'iso2_cnt'   => 'NZ',
			'iso3_cnt'   => 'NZL',
			'sort_order' => 148,
		),
		array(
			'name_cnt'   => 'Nicaragua',
			'iso2_cnt'   => 'NI',
			'iso3_cnt'   => 'NIC',
			'sort_order' => 149,
		),
		array(
			'name_cnt'   => 'Niger',
			'iso2_cnt'   => 'NE',
			'iso3_cnt'   => 'NER',
			'sort_order' => 150,
		),
		array(
			'name_cnt'   => 'Nigeria',
			'iso2_cnt'   => 'NG',
			'iso3_cnt'   => 'NGA',
			'sort_order' => 151,
		),
		array(
			'name_cnt'   => 'Niue',
			'iso2_cnt'   => 'NU',
			'iso3_cnt'   => 'NIU',
			'sort_order' => 152,
		),
		array(
			'name_cnt'   => 'Norfolk Island',
			'iso2_cnt'   => 'NF',
			'iso3_cnt'   => 'NFK',
			'sort_order' => 153,
		),
		array(
			'name_cnt'   => 'Norway',
			'iso2_cnt'   => 'NO',
			'iso3_cnt'   => 'NOR',
			'sort_order' => 154,
		),
		array(
			'name_cnt'   => 'Oman',
			'iso2_cnt'   => 'OM',
			'iso3_cnt'   => 'OMN',
			'sort_order' => 155,
		),
		array(
			'name_cnt'   => 'Pakistan',
			'iso2_cnt'   => 'PK',
			'iso3_cnt'   => 'PAK',
			'sort_order' => 156,
		),
		array(
			'name_cnt'   => 'Palau',
			'iso2_cnt'   => 'PW',
			'iso3_cnt'   => 'PLW',
			'sort_order' => 157,
		),
		array(
			'name_cnt'   => 'Panama',
			'iso2_cnt'   => 'PA',
			'iso3_cnt'   => 'PAN',
			'sort_order' => 158,
		),
		array(
			'name_cnt'   => 'Papua New Guinea',
			'iso2_cnt'   => 'PG',
			'iso3_cnt'   => 'PNG',
			'sort_order' => 159,
		),
		array(
			'name_cnt'   => 'Paraguay',
			'iso2_cnt'   => 'PY',
			'iso3_cnt'   => 'PRY',
			'sort_order' => 160,
		),
		array(
			'name_cnt'   => 'Peru',
			'iso2_cnt'   => 'PE',
			'iso3_cnt'   => 'PER',
			'sort_order' => 161,
		),
		array(
			'name_cnt'   => 'Philippines',
			'iso2_cnt'   => 'PH',
			'iso3_cnt'   => 'PHL',
			'sort_order' => 162,
		),
		array(
			'name_cnt'   => 'Pitcairn',
			'iso2_cnt'   => 'PN',
			'iso3_cnt'   => 'PCN',
			'sort_order' => 163,
		),
		array(
			'name_cnt'   => 'Poland',
			'iso2_cnt'   => 'PL',
			'iso3_cnt'   => 'POL',
			'sort_order' => 164,
		),
		array(
			'name_cnt'   => 'Portugal',
			'iso2_cnt'   => 'PT',
			'iso3_cnt'   => 'PRT',
			'sort_order' => 165,
		),
		array(
			'name_cnt'   => 'Puerto Rico',
			'iso2_cnt'   => 'PR',
			'iso3_cnt'   => 'PRI',
			'sort_order' => 166,
		),
		array(
			'name_cnt'   => 'Qatar',
			'iso2_cnt'   => 'QA',
			'iso3_cnt'   => 'QAT',
			'sort_order' => 167,
		),
		array(
			'name_cnt'   => 'Reunion',
			'iso2_cnt'   => 'RE',
			'iso3_cnt'   => 'REU',
			'sort_order' => 168,
		),
		array(
			'name_cnt'   => 'Romania',
			'iso2_cnt'   => 'RO',
			'iso3_cnt'   => 'ROM',
			'sort_order' => 169,
		),
		array(
			'name_cnt'   => 'Russian Federation',
			'iso2_cnt'   => 'RU',
			'iso3_cnt'   => 'RUS',
			'sort_order' => 170,
		),
		array(
			'name_cnt'   => 'Rwanda',
			'iso2_cnt'   => 'RW',
			'iso3_cnt'   => 'RWA',
			'sort_order' => 171,
		),
		array(
			'name_cnt'   => 'Saint Kitts and Nevis',
			'iso2_cnt'   => 'KN',
			'iso3_cnt'   => 'KNA',
			'sort_order' => 172,
		),
		array(
			'name_cnt'   => 'Saint Lucia',
			'iso2_cnt'   => 'LC',
			'iso3_cnt'   => 'LCA',
			'sort_order' => 173,
		),
		array(
			'name_cnt'   => 'Samoa',
			'iso2_cnt'   => 'WS',
			'iso3_cnt'   => 'WSM',
			'sort_order' => 174,
		),
		array(
			'name_cnt'   => 'San Marino',
			'iso2_cnt'   => 'SM',
			'iso3_cnt'   => 'SMR',
			'sort_order' => 175,
		),
		array(
			'name_cnt'   => 'Sao Tome and Principe',
			'iso2_cnt'   => 'ST',
			'iso3_cnt'   => 'STP',
			'sort_order' => 176,
		),
		array(
			'name_cnt'   => 'Saudi Arabia',
			'iso2_cnt'   => 'SA',
			'iso3_cnt'   => 'SAU',
			'sort_order' => 177,
		),
		array(
			'name_cnt'   => 'Senegal',
			'iso2_cnt'   => 'SN',
			'iso3_cnt'   => 'SEN',
			'sort_order' => 178,
		),
		array(
			'name_cnt'   => 'Seychelles',
			'iso2_cnt'   => 'SC',
			'iso3_cnt'   => 'SYC',
			'sort_order' => 179,
		),
		array(
			'name_cnt'   => 'Sierra Leone',
			'iso2_cnt'   => 'SL',
			'iso3_cnt'   => 'SLE',
			'sort_order' => 180,
		),
		array(
			'name_cnt'   => 'Singapore',
			'iso2_cnt'   => 'SG',
			'iso3_cnt'   => 'SGP',
			'sort_order' => 181,
		),
		array(
			'name_cnt'   => 'Slovakia',
			'iso2_cnt'   => 'SK',
			'iso3_cnt'   => 'SVK',
			'sort_order' => 182,
		),
		array(
			'name_cnt'   => 'Slovenia',
			'iso2_cnt'   => 'SI',
			'iso3_cnt'   => 'SVN',
			'sort_order' => 182,
		),
		array(
			'name_cnt'   => 'Solomon Islands',
			'iso2_cnt'   => 'SB',
			'iso3_cnt'   => 'SLB',
			'sort_order' => 183,
		),
		array(
			'name_cnt'   => 'Somalia',
			'iso2_cnt'   => 'SO',
			'iso3_cnt'   => 'SOM',
			'sort_order' => 184,
		),
		array(
			'name_cnt'   => 'South Africa',
			'iso2_cnt'   => 'ZA',
			'iso3_cnt'   => 'ZAF',
			'sort_order' => 185,
		),
		array(
			'name_cnt'   => 'Spain',
			'iso2_cnt'   => 'ES',
			'iso3_cnt'   => 'ESP',
			'sort_order' => 186,
		),
		array(
			'name_cnt'   => 'Sri Lanka',
			'iso2_cnt'   => 'LK',
			'iso3_cnt'   => 'LKA',
			'sort_order' => 187,
		),
		array(
			'name_cnt'   => 'St. Helena',
			'iso2_cnt'   => 'SH',
			'iso3_cnt'   => 'SHN',
			'sort_order' => 188,
		),
		array(
			'name_cnt'   => 'St. Pierre and Miquelon',
			'iso2_cnt'   => 'PM',
			'iso3_cnt'   => 'SPM',
			'sort_order' => 189,
		),
		array(
			'name_cnt'   => 'Sudan',
			'iso2_cnt'   => 'SD',
			'iso3_cnt'   => 'SDN',
			'sort_order' => 190,
		),
		array(
			'name_cnt'   => 'Suriname',
			'iso2_cnt'   => 'SR',
			'iso3_cnt'   => 'SUR',
			'sort_order' => 191,
		),
		array(
			'name_cnt'   => 'Swaziland',
			'iso2_cnt'   => 'SZ',
			'iso3_cnt'   => 'SWZ',
			'sort_order' => 192,
		),
		array(
			'name_cnt'   => 'Sweden',
			'iso2_cnt'   => 'SE',
			'iso3_cnt'   => 'SWE',
			'sort_order' => 193,
		),
		array(
			'name_cnt'   => 'Switzerland',
			'iso2_cnt'   => 'CH',
			'iso3_cnt'   => 'CHE',
			'sort_order' => 194,
		),
		array(
			'name_cnt'   => 'Syrian Arab Republic',
			'iso2_cnt'   => 'SY',
			'iso3_cnt'   => 'SYR',
			'sort_order' => 195,
		),
		array(
			'name_cnt'   => 'Taiwan',
			'iso2_cnt'   => 'TW',
			'iso3_cnt'   => 'TWN',
			'sort_order' => 196,
		),
		array(
			'name_cnt'   => 'Tajikistan',
			'iso2_cnt'   => 'TJ',
			'iso3_cnt'   => 'TJK',
			'sort_order' => 197,
		),
		array(
			'name_cnt'   => 'Thailand',
			'iso2_cnt'   => 'TH',
			'iso3_cnt'   => 'THA',
			'sort_order' => 198,
		),
		array(
			'name_cnt'   => 'Togo',
			'iso2_cnt'   => 'TG',
			'iso3_cnt'   => 'TGO',
			'sort_order' => 199,
		),
		array(
			'name_cnt'   => 'Tokelau',
			'iso2_cnt'   => 'TK',
			'iso3_cnt'   => 'TKL',
			'sort_order' => 200,
		),
		array(
			'name_cnt'   => 'Tonga',
			'iso2_cnt'   => 'TO',
			'iso3_cnt'   => 'TON',
			'sort_order' => 201,
		),
		array(
			'name_cnt'   => 'Trinidad and Tobago',
			'iso2_cnt'   => 'TT',
			'iso3_cnt'   => 'TTO',
			'sort_order' => 202,
		),
		array(
			'name_cnt'   => 'Tunisia',
			'iso2_cnt'   => 'TN',
			'iso3_cnt'   => 'TUN',
			'sort_order' => 203,
		),
		array(
			'name_cnt'   => 'Turkey',
			'iso2_cnt'   => 'TR',
			'iso3_cnt'   => 'TUR',
			'sort_order' => 204,
		),
		array(
			'name_cnt'   => 'Turkmenistan',
			'iso2_cnt'   => 'TM',
			'iso3_cnt'   => 'TKM',
			'sort_order' => 205,
		),
		array(
			'name_cnt'   => 'Turks and Caicos Islands',
			'iso2_cnt'   => 'TC',
			'iso3_cnt'   => 'TCA',
			'sort_order' => 206,
		),
		array(
			'name_cnt'   => 'Tuvalu',
			'iso2_cnt'   => 'TV',
			'iso3_cnt'   => 'TUV',
			'sort_order' => 207,
		),
		array(
			'name_cnt'   => 'Uganda',
			'iso2_cnt'   => 'UG',
			'iso3_cnt'   => 'UGA',
			'sort_order' => 208,
		),
		array(
			'name_cnt'   => 'Ukraine',
			'iso2_cnt'   => 'UA',
			'iso3_cnt'   => 'UKR',
			'sort_order' => 209,
		),
		array(
			'name_cnt'   => 'United Arab Emirates',
			'iso2_cnt'   => 'AE',
			'iso3_cnt'   => 'ARE',
			'sort_order' => 210,
		),
		array(
			'name_cnt'   => 'United Kingdom',
			'iso2_cnt'   => 'GB',
			'iso3_cnt'   => 'GBR',
			'sort_order' => 211,
		),
		array(
			'name_cnt'   => 'United States',
			'iso2_cnt'   => 'US',
			'iso3_cnt'   => 'USA',
			'sort_order' => 1,
		),
		array(
			'name_cnt'   => 'US Minor Outlying Islands',
			'iso2_cnt'   => 'UM',
			'iso3_cnt'   => 'UMI',
			'sort_order' => 213,
		),
		array(
			'name_cnt'   => 'Uruguay',
			'iso2_cnt'   => 'UY',
			'iso3_cnt'   => 'URY',
			'sort_order' => 214,
		),
		array(
			'name_cnt'   => 'Uzbekistan',
			'iso2_cnt'   => 'UZ',
			'iso3_cnt'   => 'UZB',
			'sort_order' => 215,
		),
		array(
			'name_cnt'   => 'Vanuatu',
			'iso2_cnt'   => 'VU',
			'iso3_cnt'   => 'VUT',
			'sort_order' => 216,
		),
		array(
			'name_cnt'   => 'Venezuela',
			'iso2_cnt'   => 'VE',
			'iso3_cnt'   => 'VEN',
			'sort_order' => 217,
		),
		array(
			'name_cnt'   => 'Viet Nam',
			'iso2_cnt'   => 'VN',
			'iso3_cnt'   => 'VNM',
			'sort_order' => 218,
		),
		array(
			'name_cnt'   => 'Virgin Islands (British)',
			'iso2_cnt'   => 'VG',
			'iso3_cnt'   => 'VGB',
			'sort_order' => 219,
		),
		array(
			'name_cnt'   => 'Virgin Islands (U.S.)',
			'iso2_cnt'   => 'VI',
			'iso3_cnt'   => 'VIR',
			'sort_order' => 220,
		),
		array(
			'name_cnt'   => 'Wallis and Futuna Islands',
			'iso2_cnt'   => 'WF',
			'iso3_cnt'   => 'WLF',
			'sort_order' => 221,
		),
		array(
			'name_cnt'   => 'Western Sahara',
			'iso2_cnt'   => 'EH',
			'iso3_cnt'   => 'ESH',
			'sort_order' => 222,
		),
		array(
			'name_cnt'   => 'Yemen',
			'iso2_cnt'   => 'YE',
			'iso3_cnt'   => 'YEM',
			'sort_order' => 223,
		),
		array(
			'name_cnt'   => 'Yugoslavia',
			'iso2_cnt'   => 'YU',
			'iso3_cnt'   => 'YUG',
			'sort_order' => 224,
		),
		array(
			'name_cnt'   => 'Zaire',
			'iso2_cnt'   => 'ZR',
			'iso3_cnt'   => 'ZAR',
			'sort_order' => 225,
		),
		array(
			'name_cnt'   => 'Zambia',
			'iso2_cnt'   => 'ZM',
			'iso3_cnt'   => 'ZMB',
			'sort_order' => 226,
		),
		array(
			'name_cnt'   => 'Zimbabwe',
			'iso2_cnt'   => 'ZW',
			'iso3_cnt'   => 'ZWE',
			'sort_order' => 227,
		),
	),
	'states' => array(
		array(
			'iso2_cnt'   => 'US',
			'code_sta'   => 'AL',
			'name_sta'   => 'Alabama',
			'sort_order' => 9,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'US',
			'code_sta'   => 'AK',
			'name_sta'   => 'Alaska',
			'sort_order' => 10,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'US',
			'code_sta'   => 'AZ',
			'name_sta'   => 'Arizona',
			'sort_order' => 11,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'US',
			'code_sta'   => 'AR',
			'name_sta'   => 'Arkansas',
			'sort_order' => 12,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'US',
			'code_sta'   => 'CA',
			'name_sta'   => 'California',
			'sort_order' => 13,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'US',
			'code_sta'   => 'CO',
			'name_sta'   => 'Colorado',
			'sort_order' => 14,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'US',
			'code_sta'   => 'CT',
			'name_sta'   => 'Connecticut',
			'sort_order' => 15,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'US',
			'code_sta'   => 'DE',
			'name_sta'   => 'Delaware',
			'sort_order' => 16,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'US',
			'code_sta'   => 'DC',
			'name_sta'   => 'District of Columbia',
			'sort_order' => 17,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'US',
			'code_sta'   => 'FL',
			'name_sta'   => 'Florida',
			'sort_order' => 18,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'US',
			'code_sta'   => 'GA',
			'name_sta'   => 'Georgia',
			'sort_order' => 19,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'US',
			'code_sta'   => 'HI',
			'name_sta'   => 'Hawaii',
			'sort_order' => 21,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'US',
			'code_sta'   => 'ID',
			'name_sta'   => 'Idaho',
			'sort_order' => 22,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'US',
			'code_sta'   => 'IL',
			'name_sta'   => 'Illinois',
			'sort_order' => 23,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'US',
			'code_sta'   => 'IN',
			'name_sta'   => 'Indiana',
			'sort_order' => 24,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'US',
			'code_sta'   => 'IA',
			'name_sta'   => 'Iowa',
			'sort_order' => 25,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'US',
			'code_sta'   => 'KS',
			'name_sta'   => 'Kansas',
			'sort_order' => 26,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'US',
			'code_sta'   => 'KY',
			'name_sta'   => 'Kentucky',
			'sort_order' => 27,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'US',
			'code_sta'   => 'LA',
			'name_sta'   => 'Louisiana',
			'sort_order' => 28,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'US',
			'code_sta'   => 'ME',
			'name_sta'   => 'Maine',
			'sort_order' => 29,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'US',
			'code_sta'   => 'MD',
			'name_sta'   => 'Maryland',
			'sort_order' => 30,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'US',
			'code_sta'   => 'MA',
			'name_sta'   => 'Massachusetts',
			'sort_order' => 31,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'US',
			'code_sta'   => 'MI',
			'name_sta'   => 'Michigan',
			'sort_order' => 32,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'US',
			'code_sta'   => 'MN',
			'name_sta'   => 'Minnesota',
			'sort_order' => 33,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'US',
			'code_sta'   => 'MS',
			'name_sta'   => 'Mississippi',
			'sort_order' => 34,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'US',
			'code_sta'   => 'MO',
			'name_sta'   => 'Missouri',
			'sort_order' => 35,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'US',
			'code_sta'   => 'MT',
			'name_sta'   => 'Montana',
			'sort_order' => 36,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'US',
			'code_sta'   => 'NE',
			'name_sta'   => 'Nebraska',
			'sort_order' => 37,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'US',
			'code_sta'   => 'NV',
			'name_sta'   => 'Nevada',
			'sort_order' => 38,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'US',
			'code_sta'   => 'NH',
			'name_sta'   => 'New Hampshire',
			'sort_order' => 39,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'US',
			'code_sta'   => 'NJ',
			'name_sta'   => 'New Jersey',
			'sort_order' => 40,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'US',
			'code_sta'   => 'NM',
			'name_sta'   => 'New Mexico',
			'sort_order' => 41,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'US',
			'code_sta'   => 'NY',
			'name_sta'   => 'New York',
			'sort_order' => 42,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'US',
			'code_sta'   => 'NC',
			'name_sta'   => 'North Carolina',
			'sort_order' => 43,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'US',
			'code_sta'   => 'ND',
			'name_sta'   => 'North Dakota',
			'sort_order' => 44,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'US',
			'code_sta'   => 'OH',
			'name_sta'   => 'Ohio',
			'sort_order' => 45,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'US',
			'code_sta'   => 'OK',
			'name_sta'   => 'Oklahoma',
			'sort_order' => 46,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'US',
			'code_sta'   => 'OR',
			'name_sta'   => 'Oregon',
			'sort_order' => 47,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'US',
			'code_sta'   => 'PA',
			'name_sta'   => 'Pennsylvania',
			'sort_order' => 48,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'US',
			'code_sta'   => 'PR',
			'name_sta'   => 'Puerto Rico',
			'sort_order' => 49,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'US',
			'code_sta'   => 'RI',
			'name_sta'   => 'Rhode Island',
			'sort_order' => 50,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'US',
			'code_sta'   => 'SC',
			'name_sta'   => 'South Carolina',
			'sort_order' => 51,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'US',
			'code_sta'   => 'SD',
			'name_sta'   => 'South Dakota',
			'sort_order' => 52,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'US',
			'code_sta'   => 'TN',
			'name_sta'   => 'Tennessee',
			'sort_order' => 53,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'US',
			'code_sta'   => 'TX',
			'name_sta'   => 'Texas',
			'sort_order' => 54,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'US',
			'code_sta'   => 'UT',
			'name_sta'   => 'Utah',
			'sort_order' => 55,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'US',
			'code_sta'   => 'VT',
			'name_sta'   => 'Vermont',
			'sort_order' => 56,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'US',
			'code_sta'   => 'VI',
			'name_sta'   => 'Virgin Islands',
			'sort_order' => 57,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'US',
			'code_sta'   => 'VA',
			'name_sta'   => 'Virginia',
			'sort_order' => 58,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'US',
			'code_sta'   => 'WA',
			'name_sta'   => 'Washington',
			'sort_order' => 59,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'US',
			'code_sta'   => 'WV',
			'name_sta'   => 'West Virginia',
			'sort_order' => 60,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'US',
			'code_sta'   => 'WI',
			'name_sta'   => 'Wisconsin',
			'sort_order' => 61,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'US',
			'code_sta'   => 'WY',
			'name_sta'   => 'Wyoming',
			'sort_order' => 62,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'CA',
			'code_sta'   => 'AB',
			'name_sta'   => 'Alberta',
			'sort_order' => 100,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'CA',
			'code_sta'   => 'BC',
			'name_sta'   => 'British Columbia',
			'sort_order' => 101,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'CA',
			'code_sta'   => 'MB',
			'name_sta'   => 'Manitoba',
			'sort_order' => 102,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'CA',
			'code_sta'   => 'NF',
			'name_sta'   => 'Newfoundland',
			'sort_order' => 103,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'CA',
			'code_sta'   => 'NB',
			'name_sta'   => 'New Brunswick',
			'sort_order' => 104,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'CA',
			'code_sta'   => 'NS',
			'name_sta'   => 'Nova Scotia',
			'sort_order' => 105,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'CA',
			'code_sta'   => 'NT',
			'name_sta'   => 'Northwest Territories',
			'sort_order' => 106,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'CA',
			'code_sta'   => 'NU',
			'name_sta'   => 'Nunavut',
			'sort_order' => 107,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'CA',
			'code_sta'   => 'ON',
			'name_sta'   => 'Ontario',
			'sort_order' => 108,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'CA',
			'code_sta'   => 'PE',
			'name_sta'   => 'Prince Edward Island',
			'sort_order' => 109,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'CA',
			'code_sta'   => 'QC',
			'name_sta'   => 'Quebec',
			'sort_order' => 110,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'CA',
			'code_sta'   => 'SK',
			'name_sta'   => 'Saskatchewan',
			'sort_order' => 111,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'CA',
			'code_sta'   => 'YT',
			'name_sta'   => 'Yukon Territory',
			'sort_order' => 112,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'AU',
			'code_sta'   => 'ACT',
			'name_sta'   => 'Australian Capital Territory',
			'sort_order' => 113,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'AU',
			'code_sta'   => 'CX',
			'name_sta'   => 'Christmas Island',
			'sort_order' => 114,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'AU',
			'code_sta'   => 'CC',
			'name_sta'   => 'Cocos Islands',
			'sort_order' => 115,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'AU',
			'code_sta'   => 'HM',
			'name_sta'   => 'Heard Island and McDonald Islands',
			'sort_order' => 116,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'AU',
			'code_sta'   => 'NSW',
			'name_sta'   => 'New South Wales',
			'sort_order' => 117,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'AU',
			'code_sta'   => 'NF',
			'name_sta'   => 'Norfolk Island',
			'sort_order' => 118,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'AU',
			'code_sta'   => 'NT',
			'name_sta'   => 'Northern Territory',
			'sort_order' => 119,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'AU',
			'code_sta'   => 'QLD',
			'name_sta'   => 'Queensland',
			'sort_order' => 120,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'AU',
			'code_sta'   => 'SA',
			'name_sta'   => 'South Australia',
			'sort_order' => 121,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'AU',
			'code_sta'   => 'TAS',
			'name_sta'   => 'Tasmania',
			'sort_order' => 122,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'AU',
			'code_sta'   => 'VIC',
			'name_sta'   => 'Victoria',
			'sort_order' => 123,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'AU',
			'code_sta'   => 'WA',
			'name_sta'   => 'Western Australia',
			'sort_order' => 124,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'GB',
			'code_sta'   => 'Avon',
			'name_sta'   => 'Avon',
			'sort_order' => 125,
			'group_sta'  => 'England',
		),
		array(
			'iso2_cnt'   => 'GB',
			'code_sta'   => 'Bedfordshire',
			'name_sta'   => 'Bedfordshire',
			'sort_order' => 126,
			'group_sta'  => 'England',
		),
		array(
			'iso2_cnt'   => 'GB',
			'code_sta'   => 'Berkshire',
			'name_sta'   => 'Berkshire',
			'sort_order' => 127,
			'group_sta'  => 'England',
		),
		array(
			'iso2_cnt'   => 'GB',
			'code_sta'   => 'Buckinghamshire',
			'name_sta'   => 'Buckinghamshire',
			'sort_order' => 128,
			'group_sta'  => 'England',
		),
		array(
			'iso2_cnt'   => 'GB',
			'code_sta'   => 'Cambridgeshire',
			'name_sta'   => 'Cambridgeshire',
			'sort_order' => 129,
			'group_sta'  => 'England',
		),
		array(
			'iso2_cnt'   => 'GB',
			'code_sta'   => 'Cheshire',
			'name_sta'   => 'Cheshire',
			'sort_order' => 130,
			'group_sta'  => 'England',
		),
		array(
			'iso2_cnt'   => 'GB',
			'code_sta'   => 'Cleveland',
			'name_sta'   => 'Cleveland',
			'sort_order' => 131,
			'group_sta'  => 'England',
		),
		array(
			'iso2_cnt'   => 'GB',
			'code_sta'   => 'Cornwall',
			'name_sta'   => 'Cornwall',
			'sort_order' => 132,
			'group_sta'  => 'England',
		),
		array(
			'iso2_cnt'   => 'GB',
			'code_sta'   => 'Cumbria',
			'name_sta'   => 'Cumbria',
			'sort_order' => 133,
			'group_sta'  => 'England',
		),
		array(
			'iso2_cnt'   => 'GB',
			'code_sta'   => 'Derbyshire',
			'name_sta'   => 'Derbyshire',
			'sort_order' => 134,
			'group_sta'  => 'England',
		),
		array(
			'iso2_cnt'   => 'GB',
			'code_sta'   => 'Devon',
			'name_sta'   => 'Devon',
			'sort_order' => 135,
			'group_sta'  => 'England',
		),
		array(
			'iso2_cnt'   => 'GB',
			'code_sta'   => 'Dorset',
			'name_sta'   => 'Dorset',
			'sort_order' => 136,
			'group_sta'  => 'England',
		),
		array(
			'iso2_cnt'   => 'GB',
			'code_sta'   => 'Durham',
			'name_sta'   => 'Durham',
			'sort_order' => 137,
			'group_sta'  => 'England',
		),
		array(
			'iso2_cnt'   => 'GB',
			'code_sta'   => 'East Sussex',
			'name_sta'   => 'East Sussex',
			'sort_order' => 138,
			'group_sta'  => 'England',
		),
		array(
			'iso2_cnt'   => 'GB',
			'code_sta'   => 'Essex',
			'name_sta'   => 'Essex',
			'sort_order' => 139,
			'group_sta'  => 'England',
		),
		array(
			'iso2_cnt'   => 'GB',
			'code_sta'   => 'Gloucestershire',
			'name_sta'   => 'Gloucestershire',
			'sort_order' => 140,
			'group_sta'  => 'England',
		),
		array(
			'iso2_cnt'   => 'GB',
			'code_sta'   => 'Hampshire',
			'name_sta'   => 'Hampshire',
			'sort_order' => 141,
			'group_sta'  => 'England',
		),
		array(
			'iso2_cnt'   => 'GB',
			'code_sta'   => 'Herefordshire',
			'name_sta'   => 'Herefordshire',
			'sort_order' => 142,
			'group_sta'  => 'England',
		),
		array(
			'iso2_cnt'   => 'GB',
			'code_sta'   => 'Hertfordshire',
			'name_sta'   => 'Hertfordshire',
			'sort_order' => 143,
			'group_sta'  => 'England',
		),
		array(
			'iso2_cnt'   => 'GB',
			'code_sta'   => 'Isle of Wight',
			'name_sta'   => 'Isle of Wight',
			'sort_order' => 144,
			'group_sta'  => 'England',
		),
		array(
			'iso2_cnt'   => 'GB',
			'code_sta'   => 'Kent',
			'name_sta'   => 'Kent',
			'sort_order' => 145,
			'group_sta'  => 'England',
		),
		array(
			'iso2_cnt'   => 'GB',
			'code_sta'   => 'Lancashire',
			'name_sta'   => 'Lancashire',
			'sort_order' => 146,
			'group_sta'  => 'England',
		),
		array(
			'iso2_cnt'   => 'GB',
			'code_sta'   => 'Leicestershire',
			'name_sta'   => 'Leicestershire',
			'sort_order' => 147,
			'group_sta'  => 'England',
		),
		array(
			'iso2_cnt'   => 'GB',
			'code_sta'   => 'Lincolnshire',
			'name_sta'   => 'Lincolnshire',
			'sort_order' => 148,
			'group_sta'  => 'England',
		),
		array(
			'iso2_cnt'   => 'GB',
			'code_sta'   => 'London',
			'name_sta'   => 'London',
			'sort_order' => 149,
			'group_sta'  => 'England',
		),
		array(
			'iso2_cnt'   => 'GB',
			'code_sta'   => 'Merseyside',
			'name_sta'   => 'Merseyside',
			'sort_order' => 150,
			'group_sta'  => 'England',
		),
		array(
			'iso2_cnt'   => 'GB',
			'code_sta'   => 'Middlesex',
			'name_sta'   => 'Middlesex',
			'sort_order' => 151,
			'group_sta'  => 'England',
		),
		array(
			'iso2_cnt'   => 'GB',
			'code_sta'   => 'Norfolk',
			'name_sta'   => 'Norfolk',
			'sort_order' => 152,
			'group_sta'  => 'England',
		),
		array(
			'iso2_cnt'   => 'GB',
			'code_sta'   => 'Northamptonshire',
			'name_sta'   => 'Northamptonshire',
			'sort_order' => 153,
			'group_sta'  => 'England',
		),
		array(
			'iso2_cnt'   => 'GB',
			'code_sta'   => 'Northumberland',
			'name_sta'   => 'Northumberland',
			'sort_order' => 154,
			'group_sta'  => 'England',
		),
		array(
			'iso2_cnt'   => 'GB',
			'code_sta'   => 'North Humberside',
			'name_sta'   => 'North Humberside',
			'sort_order' => 155,
			'group_sta'  => 'England',
		),
		array(
			'iso2_cnt'   => 'GB',
			'code_sta'   => 'North Yorkshire',
			'name_sta'   => 'North Yorkshire',
			'sort_order' => 156,
			'group_sta'  => 'England',
		),
		array(
			'iso2_cnt'   => 'GB',
			'code_sta'   => 'Nottinghamshire',
			'name_sta'   => 'Nottinghamshire',
			'sort_order' => 157,
			'group_sta'  => 'England',
		),
		array(
			'iso2_cnt'   => 'GB',
			'code_sta'   => 'Oxfordshire',
			'name_sta'   => 'Oxfordshire',
			'sort_order' => 158,
			'group_sta'  => 'England',
		),
		array(
			'iso2_cnt'   => 'GB',
			'code_sta'   => 'Rutland',
			'name_sta'   => 'Rutland',
			'sort_order' => 159,
			'group_sta'  => 'England',
		),
		array(
			'iso2_cnt'   => 'GB',
			'code_sta'   => 'Shropshire',
			'name_sta'   => 'Shropshire',
			'sort_order' => 160,
			'group_sta'  => 'England',
		),
		array(
			'iso2_cnt'   => 'GB',
			'code_sta'   => 'Somerset',
			'name_sta'   => 'Somerset',
			'sort_order' => 161,
			'group_sta'  => 'England',
		),
		array(
			'iso2_cnt'   => 'GB',
			'code_sta'   => 'South Humberside',
			'name_sta'   => 'South Humberside',
			'sort_order' => 162,
			'group_sta'  => 'England',
		),
		array(
			'iso2_cnt'   => 'GB',
			'code_sta'   => 'South Yorkshire',
			'name_sta'   => 'South Yorkshire',
			'sort_order' => 163,
			'group_sta'  => 'England',
		),
		array(
			'iso2_cnt'   => 'GB',
			'code_sta'   => 'Staffordshire',
			'name_sta'   => 'Staffordshire',
			'sort_order' => 164,
			'group_sta'  => 'England',
		),
		array(
			'iso2_cnt'   => 'GB',
			'code_sta'   => 'Suffolk',
			'name_sta'   => 'Suffolk',
			'sort_order' => 165,
			'group_sta'  => 'England',
		),
		array(
			'iso2_cnt'   => 'GB',
			'code_sta'   => 'Surrey',
			'name_sta'   => 'Surrey',
			'sort_order' => 166,
			'group_sta'  => 'England',
		),
		array(
			'iso2_cnt'   => 'GB',
			'code_sta'   => 'Tyne and Wear',
			'name_sta'   => 'Tyne and Wear',
			'sort_order' => 167,
			'group_sta'  => 'England',
		),
		array(
			'iso2_cnt'   => 'GB',
			'code_sta'   => 'Warwickshire',
			'name_sta'   => 'Warwickshire',
			'sort_order' => 168,
			'group_sta'  => 'England',
		),
		array(
			'iso2_cnt'   => 'GB',
			'code_sta'   => 'West Midlands',
			'name_sta'   => 'West Midlands',
			'sort_order' => 169,
			'group_sta'  => 'England',
		),
		array(
			'iso2_cnt'   => 'GB',
			'code_sta'   => 'West Sussex',
			'name_sta'   => 'West Sussex',
			'sort_order' => 170,
			'group_sta'  => 'England',
		),
		array(
			'iso2_cnt'   => 'GB',
			'code_sta'   => 'West Yorkshire',
			'name_sta'   => 'West Yorkshire',
			'sort_order' => 171,
			'group_sta'  => 'England',
		),
		array(
			'iso2_cnt'   => 'GB',
			'code_sta'   => 'Wiltshire',
			'name_sta'   => 'Wiltshire',
			'sort_order' => 172,
			'group_sta'  => 'England',
		),
		array(
			'iso2_cnt'   => 'GB',
			'code_sta'   => 'Worcestershire',
			'name_sta'   => 'Worcestershire',
			'sort_order' => 173,
			'group_sta'  => 'England',
		),
		array(
			'iso2_cnt'   => 'GB',
			'code_sta'   => 'Clwyd',
			'name_sta'   => 'Clwyd',
			'sort_order' => 174,
			'group_sta'  => 'Wales',
		),
		array(
			'iso2_cnt'   => 'GB',
			'code_sta'   => 'Dyfed',
			'name_sta'   => 'Dyfed',
			'sort_order' => 175,
			'group_sta'  => 'Wales',
		),
		array(
			'iso2_cnt'   => 'GB',
			'code_sta'   => 'Gwent',
			'name_sta'   => 'Gwent',
			'sort_order' => 176,
			'group_sta'  => 'Wales',
		),
		array(
			'iso2_cnt'   => 'GB',
			'code_sta'   => 'Gwynedd',
			'name_sta'   => 'Gwynedd',
			'sort_order' => 177,
			'group_sta'  => 'Wales',
		),
		array(
			'iso2_cnt'   => 'GB',
			'code_sta'   => 'Mid Glamorgan',
			'name_sta'   => 'Mid Glamorgan',
			'sort_order' => 178,
			'group_sta'  => 'Wales',
		),
		array(
			'iso2_cnt'   => 'GB',
			'code_sta'   => 'Powys',
			'name_sta'   => 'Powys',
			'sort_order' => 179,
			'group_sta'  => 'Wales',
		),
		array(
			'iso2_cnt'   => 'GB',
			'code_sta'   => 'South Glamorgan',
			'name_sta'   => 'South Glamorgan',
			'sort_order' => 180,
			'group_sta'  => 'Wales',
		),
		array(
			'iso2_cnt'   => 'GB',
			'code_sta'   => 'West Glamorgan',
			'name_sta'   => 'West Glamorgan',
			'sort_order' => 181,
			'group_sta'  => 'Wales',
		),
		array(
			'iso2_cnt'   => 'GB',
			'code_sta'   => 'Aberdeenshire',
			'name_sta'   => 'Aberdeenshire',
			'sort_order' => 182,
			'group_sta'  => 'Scotland',
		),
		array(
			'iso2_cnt'   => 'GB',
			'code_sta'   => 'Angus',
			'name_sta'   => 'Angus',
			'sort_order' => 183,
			'group_sta'  => 'Scotland',
		),
		array(
			'iso2_cnt'   => 'GB',
			'code_sta'   => 'Argyll',
			'name_sta'   => 'Argyll',
			'sort_order' => 184,
			'group_sta'  => 'Scotland',
		),
		array(
			'iso2_cnt'   => 'GB',
			'code_sta'   => 'Ayrshire',
			'name_sta'   => 'Ayrshire',
			'sort_order' => 185,
			'group_sta'  => 'Scotland',
		),
		array(
			'iso2_cnt'   => 'GB',
			'code_sta'   => 'Banffshire',
			'name_sta'   => 'Banffshire',
			'sort_order' => 186,
			'group_sta'  => 'Scotland',
		),
		array(
			'iso2_cnt'   => 'GB',
			'code_sta'   => 'Berwickshire',
			'name_sta'   => 'Berwickshire',
			'sort_order' => 187,
			'group_sta'  => 'Scotland',
		),
		array(
			'iso2_cnt'   => 'GB',
			'code_sta'   => 'Bute',
			'name_sta'   => 'Bute',
			'sort_order' => 188,
			'group_sta'  => 'Scotland',
		),
		array(
			'iso2_cnt'   => 'GB',
			'code_sta'   => 'Caithness',
			'name_sta'   => 'Caithness',
			'sort_order' => 189,
			'group_sta'  => 'Scotland',
		),
		array(
			'iso2_cnt'   => 'GB',
			'code_sta'   => 'Clackmannanshire',
			'name_sta'   => 'Clackmannanshire',
			'sort_order' => 190,
			'group_sta'  => 'Scotland',
		),
		array(
			'iso2_cnt'   => 'GB',
			'code_sta'   => 'Dumfriesshire',
			'name_sta'   => 'Dumfriesshire',
			'sort_order' => 191,
			'group_sta'  => 'Scotland',
		),
		array(
			'iso2_cnt'   => 'GB',
			'code_sta'   => 'Dunbartonshire',
			'name_sta'   => 'Dunbartonshire',
			'sort_order' => 192,
			'group_sta'  => 'Scotland',
		),
		array(
			'iso2_cnt'   => 'GB',
			'code_sta'   => 'East Lothian',
			'name_sta'   => 'East Lothian',
			'sort_order' => 193,
			'group_sta'  => 'Scotland',
		),
		array(
			'iso2_cnt'   => 'GB',
			'code_sta'   => 'Fife',
			'name_sta'   => 'Fife',
			'sort_order' => 194,
			'group_sta'  => 'Scotland',
		),
		array(
			'iso2_cnt'   => 'GB',
			'code_sta'   => 'Inverness-shire',
			'name_sta'   => 'Inverness-shire',
			'sort_order' => 195,
			'group_sta'  => 'Scotland',
		),
		array(
			'iso2_cnt'   => 'GB',
			'code_sta'   => 'Kincardineshire',
			'name_sta'   => 'Kincardineshire',
			'sort_order' => 196,
			'group_sta'  => 'Scotland',
		),
		array(
			'iso2_cnt'   => 'GB',
			'code_sta'   => 'Kinross-shire',
			'name_sta'   => 'Kinross-shire',
			'sort_order' => 197,
			'group_sta'  => 'Scotland',
		),
		array(
			'iso2_cnt'   => 'GB',
			'code_sta'   => 'Kirkcudbrightshire',
			'name_sta'   => 'Kirkcudbrightshire',
			'sort_order' => 198,
			'group_sta'  => 'Scotland',
		),
		array(
			'iso2_cnt'   => 'GB',
			'code_sta'   => 'Lanarkshire',
			'name_sta'   => 'Lanarkshire',
			'sort_order' => 199,
			'group_sta'  => 'Scotland',
		),
		array(
			'iso2_cnt'   => 'GB',
			'code_sta'   => 'Midlothian',
			'name_sta'   => 'Midlothian',
			'sort_order' => 200,
			'group_sta'  => 'Scotland',
		),
		array(
			'iso2_cnt'   => 'GB',
			'code_sta'   => 'Moray',
			'name_sta'   => 'Moray',
			'sort_order' => 201,
			'group_sta'  => 'Scotland',
		),
		array(
			'iso2_cnt'   => 'GB',
			'code_sta'   => 'Nairnshire',
			'name_sta'   => 'Nairnshire',
			'sort_order' => 202,
			'group_sta'  => 'Scotland',
		),
		array(
			'iso2_cnt'   => 'GB',
			'code_sta'   => 'Orkney',
			'name_sta'   => 'Orkney',
			'sort_order' => 203,
			'group_sta'  => 'Scotland',
		),
		array(
			'iso2_cnt'   => 'GB',
			'code_sta'   => 'Peeblesshire',
			'name_sta'   => 'Peeblesshire',
			'sort_order' => 204,
			'group_sta'  => 'Scotland',
		),
		array(
			'iso2_cnt'   => 'GB',
			'code_sta'   => 'Perthshire',
			'name_sta'   => 'Perthshire',
			'sort_order' => 205,
			'group_sta'  => 'Scotland',
		),
		array(
			'iso2_cnt'   => 'GB',
			'code_sta'   => 'Renfrewshire',
			'name_sta'   => 'Renfrewshire',
			'sort_order' => 206,
			'group_sta'  => 'Scotland',
		),
		array(
			'iso2_cnt'   => 'GB',
			'code_sta'   => 'Ross-shire',
			'name_sta'   => 'Ross-shire',
			'sort_order' => 207,
			'group_sta'  => 'Scotland',
		),
		array(
			'iso2_cnt'   => 'GB',
			'code_sta'   => 'Roxburghshire',
			'name_sta'   => 'Roxburghshire',
			'sort_order' => 208,
			'group_sta'  => 'Scotland',
		),
		array(
			'iso2_cnt'   => 'GB',
			'code_sta'   => 'Selkirkshire',
			'name_sta'   => 'Selkirkshire',
			'sort_order' => 209,
			'group_sta'  => 'Scotland',
		),
		array(
			'iso2_cnt'   => 'GB',
			'code_sta'   => 'Shetland',
			'name_sta'   => 'Shetland',
			'sort_order' => 210,
			'group_sta'  => 'Scotland',
		),
		array(
			'iso2_cnt'   => 'GB',
			'code_sta'   => 'Stirlingshire',
			'name_sta'   => 'Stirlingshire',
			'sort_order' => 211,
			'group_sta'  => 'Scotland',
		),
		array(
			'iso2_cnt'   => 'GB',
			'code_sta'   => 'Sutherland',
			'name_sta'   => 'Sutherland',
			'sort_order' => 212,
			'group_sta'  => 'Scotland',
		),
		array(
			'iso2_cnt'   => 'GB',
			'code_sta'   => 'West Lothian',
			'name_sta'   => 'West Lothian',
			'sort_order' => 213,
			'group_sta'  => 'Scotland',
		),
		array(
			'iso2_cnt'   => 'GB',
			'code_sta'   => 'Wigtownshire',
			'name_sta'   => 'Wigtownshire',
			'sort_order' => 214,
			'group_sta'  => 'Scotland',
		),
		array(
			'iso2_cnt'   => 'GB',
			'code_sta'   => 'Antrim',
			'name_sta'   => 'Antrim',
			'sort_order' => 215,
			'group_sta'  => 'Northern Ireland',
		),
		array(
			'iso2_cnt'   => 'GB',
			'code_sta'   => 'Down',
			'name_sta'   => 'Down',
			'sort_order' => 217,
			'group_sta'  => 'Northern Ireland',
		),
		array(
			'iso2_cnt'   => 'GB',
			'code_sta'   => 'Armagh',
			'name_sta'   => 'Armagh',
			'sort_order' => 216,
			'group_sta'  => 'Northern Ireland',
		),
		array(
			'iso2_cnt'   => 'GB',
			'code_sta'   => 'Fermanagh',
			'name_sta'   => 'Fermanagh',
			'sort_order' => 218,
			'group_sta'  => 'Northern Ireland',
		),
		array(
			'iso2_cnt'   => 'GB',
			'code_sta'   => 'Londonderry',
			'name_sta'   => 'Londonderry',
			'sort_order' => 219,
			'group_sta'  => 'Northern Ireland',
		),
		array(
			'iso2_cnt'   => 'GB',
			'code_sta'   => 'Tyrone',
			'name_sta'   => 'Tyrone',
			'sort_order' => 220,
			'group_sta'  => 'Northern Ireland',
		),
		array(
			'iso2_cnt'   => 'BR',
			'code_sta'   => 'AL',
			'name_sta'   => 'Alagoas',
			'sort_order' => 221,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'BR',
			'code_sta'   => 'AM',
			'name_sta'   => 'Amazonas',
			'sort_order' => 222,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'BR',
			'code_sta'   => 'BA',
			'name_sta'   => 'Bahia',
			'sort_order' => 223,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'BR',
			'code_sta'   => 'CE',
			'name_sta'   => 'Cearà',
			'sort_order' => 224,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'BR',
			'code_sta'   => 'DF',
			'name_sta'   => 'Distrito Federal',
			'sort_order' => 225,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'BR',
			'code_sta'   => 'ES',
			'name_sta'   => 'Espìrito Santo',
			'sort_order' => 226,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'BR',
			'code_sta'   => 'GO',
			'name_sta'   => 'Goias',
			'sort_order' => 227,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'BR',
			'code_sta'   => 'MA',
			'name_sta'   => 'Maranhao',
			'sort_order' => 228,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'BR',
			'code_sta'   => 'MT',
			'name_sta'   => 'Mato Grosso',
			'sort_order' => 229,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'BR',
			'code_sta'   => 'MS',
			'name_sta'   => 'Mato Grosso Do Sul',
			'sort_order' => 230,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'BR',
			'code_sta'   => 'MG',
			'name_sta'   => 'Minas Gerais',
			'sort_order' => 231,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'BR',
			'code_sta'   => 'PA',
			'name_sta'   => 'Parà',
			'sort_order' => 232,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'BR',
			'code_sta'   => 'PB',
			'name_sta'   => 'Paraìba',
			'sort_order' => 233,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'BR',
			'code_sta'   => 'PR',
			'name_sta'   => 'Paranà',
			'sort_order' => 234,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'BR',
			'code_sta'   => 'PE',
			'name_sta'   => 'Pernambuco',
			'sort_order' => 235,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'BR',
			'code_sta'   => 'PI',
			'name_sta'   => 'Piauì',
			'sort_order' => 236,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'BR',
			'code_sta'   => 'RJ',
			'name_sta'   => 'Rio de Janeiro',
			'sort_order' => 237,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'BR',
			'code_sta'   => 'RN',
			'name_sta'   => 'Rio Grande do Norte',
			'sort_order' => 238,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'BR',
			'code_sta'   => 'RS',
			'name_sta'   => 'Dio Grande do Sul',
			'sort_order' => 239,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'BR',
			'code_sta'   => 'RO',
			'name_sta'   => 'Rondônia',
			'sort_order' => 240,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'BR',
			'code_sta'   => 'SC',
			'name_sta'   => 'Santa Catarina',
			'sort_order' => 241,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'BR',
			'code_sta'   => 'SP',
			'name_sta'   => 'Sao Paulo',
			'sort_order' => 242,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'BR',
			'code_sta'   => 'SE',
			'name_sta'   => 'Sergipe',
			'sort_order' => 243,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'CN',
			'code_sta'   => 'ANH',
			'name_sta'   => 'Anhui',
			'sort_order' => 244,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'CN',
			'code_sta'   => 'BEI',
			'name_sta'   => 'Beijing',
			'sort_order' => 245,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'CN',
			'code_sta'   => 'CHO',
			'name_sta'   => 'Chongqing',
			'sort_order' => 246,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'CN',
			'code_sta'   => 'FUJ',
			'name_sta'   => 'Fujian',
			'sort_order' => 247,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'CN',
			'code_sta'   => 'GAN',
			'name_sta'   => 'Gansu',
			'sort_order' => 248,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'CN',
			'code_sta'   => 'GDG',
			'name_sta'   => 'Guangdong',
			'sort_order' => 249,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'CN',
			'code_sta'   => 'GXI',
			'name_sta'   => 'Guangxi',
			'sort_order' => 250,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'CN',
			'code_sta'   => 'GUI',
			'name_sta'   => 'Guizhou',
			'sort_order' => 251,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'CN',
			'code_sta'   => 'HAI',
			'name_sta'   => 'Hainan',
			'sort_order' => 252,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'CN',
			'code_sta'   => 'HEB',
			'name_sta'   => 'Hebei',
			'sort_order' => 253,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'CN',
			'code_sta'   => 'HEI',
			'name_sta'   => 'Heilongjiang',
			'sort_order' => 254,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'CN',
			'code_sta'   => 'HEN',
			'name_sta'   => 'Henan',
			'sort_order' => 255,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'CN',
			'code_sta'   => 'HUB',
			'name_sta'   => 'Hubei',
			'sort_order' => 256,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'CN',
			'code_sta'   => 'HUN',
			'name_sta'   => 'Hunan',
			'sort_order' => 257,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'CN',
			'code_sta'   => 'JSU',
			'name_sta'   => 'Jiangsu',
			'sort_order' => 258,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'CN',
			'code_sta'   => 'JXI',
			'name_sta'   => 'Jiangxi',
			'sort_order' => 259,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'CN',
			'code_sta'   => 'JIL',
			'name_sta'   => 'Jilin',
			'sort_order' => 260,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'CN',
			'code_sta'   => 'LIA',
			'name_sta'   => 'Liaoning',
			'sort_order' => 261,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'CN',
			'code_sta'   => 'MON',
			'name_sta'   => 'Nei Mongol',
			'sort_order' => 262,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'CN',
			'code_sta'   => 'NIN',
			'name_sta'   => 'Ningxia',
			'sort_order' => 263,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'CN',
			'code_sta'   => 'QIN',
			'name_sta'   => 'Qinghai',
			'sort_order' => 264,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'CN',
			'code_sta'   => 'SHA',
			'name_sta'   => 'Shaanxi',
			'sort_order' => 265,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'CN',
			'code_sta'   => 'SHD',
			'name_sta'   => 'Shandong',
			'sort_order' => 266,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'CN',
			'code_sta'   => 'SHH',
			'name_sta'   => 'Shanghai',
			'sort_order' => 267,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'CN',
			'code_sta'   => 'SHX',
			'name_sta'   => 'Shanxi',
			'sort_order' => 268,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'CN',
			'code_sta'   => 'SIC',
			'name_sta'   => 'Sichuan',
			'sort_order' => 269,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'CN',
			'code_sta'   => 'TIA',
			'name_sta'   => 'TIanjin',
			'sort_order' => 270,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'CN',
			'code_sta'   => 'XIN',
			'name_sta'   => 'Xinjiang',
			'sort_order' => 271,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'CN',
			'code_sta'   => 'XIZ',
			'name_sta'   => 'Xizang',
			'sort_order' => 272,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'CN',
			'code_sta'   => 'YUN',
			'name_sta'   => 'Yunnan',
			'sort_order' => 273,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'CN',
			'code_sta'   => 'ZHE',
			'name_sta'   => 'Zhejiang',
			'sort_order' => 274,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'IN',
			'code_sta'   => 'AND',
			'name_sta'   => 'Andhra Pradesh',
			'sort_order' => 275,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'IN',
			'code_sta'   => 'ASS',
			'name_sta'   => 'Assam',
			'sort_order' => 276,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'IN',
			'code_sta'   => 'BIH',
			'name_sta'   => 'Bihar',
			'sort_order' => 277,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'IN',
			'code_sta'   => 'CHH',
			'name_sta'   => 'Chhattisgarh',
			'sort_order' => 278,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'IN',
			'code_sta'   => 'DEL',
			'name_sta'   => 'Delhi',
			'sort_order' => 279,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'IN',
			'code_sta'   => 'GOA',
			'name_sta'   => 'Goa',
			'sort_order' => 280,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'IN',
			'code_sta'   => 'GUJ',
			'name_sta'   => 'Gujarat',
			'sort_order' => 281,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'IN',
			'code_sta'   => 'HAR',
			'name_sta'   => 'Haryana',
			'sort_order' => 282,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'IN',
			'code_sta'   => 'HIM',
			'name_sta'   => 'Himachal Pradesh',
			'sort_order' => 283,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'IN',
			'code_sta'   => 'JAM',
			'name_sta'   => 'Jammu & Kashmir',
			'sort_order' => 284,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'IN',
			'code_sta'   => 'JHA',
			'name_sta'   => 'Jharkhand',
			'sort_order' => 285,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'IN',
			'code_sta'   => 'KAR',
			'name_sta'   => 'Karnataka',
			'sort_order' => 286,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'IN',
			'code_sta'   => 'KER',
			'name_sta'   => 'Kerala',
			'sort_order' => 287,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'IN',
			'code_sta'   => 'MAD',
			'name_sta'   => 'Madhya Pradesh',
			'sort_order' => 288,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'IN',
			'code_sta'   => 'MAH',
			'name_sta'   => 'Maharashtra',
			'sort_order' => 289,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'IN',
			'code_sta'   => 'MEG',
			'name_sta'   => 'Meghalaya',
			'sort_order' => 290,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'IN',
			'code_sta'   => 'ORI',
			'name_sta'   => 'Orissa',
			'sort_order' => 291,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'IN',
			'code_sta'   => 'PON',
			'name_sta'   => 'Pondicherry',
			'sort_order' => 292,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'IN',
			'code_sta'   => 'PUN',
			'name_sta'   => 'Punjab',
			'sort_order' => 293,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'IN',
			'code_sta'   => 'RAJ',
			'name_sta'   => 'Rajasthan',
			'sort_order' => 294,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'IN',
			'code_sta'   => 'TAM',
			'name_sta'   => 'Tamil Nadu',
			'sort_order' => 295,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'IN',
			'code_sta'   => 'UTT',
			'name_sta'   => 'Uttar Pradesh',
			'sort_order' => 296,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'IN',
			'code_sta'   => 'UTR',
			'name_sta'   => 'Uttaranchal',
			'sort_order' => 297,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'IN',
			'code_sta'   => 'WES',
			'name_sta'   => 'West Bengal',
			'sort_order' => 298,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'JP',
			'code_sta'   => 'AIC',
			'name_sta'   => 'Aichi',
			'sort_order' => 299,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'JP',
			'code_sta'   => 'AKT',
			'name_sta'   => 'Akita',
			'sort_order' => 300,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'JP',
			'code_sta'   => 'AMR',
			'name_sta'   => 'Aomori',
			'sort_order' => 301,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'JP',
			'code_sta'   => 'CHB',
			'name_sta'   => 'Chiba',
			'sort_order' => 302,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'JP',
			'code_sta'   => 'EHM',
			'name_sta'   => 'Ehime',
			'sort_order' => 303,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'JP',
			'code_sta'   => 'FKI',
			'name_sta'   => 'Fukui',
			'sort_order' => 304,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'JP',
			'code_sta'   => 'FKO',
			'name_sta'   => 'Fukuoka',
			'sort_order' => 305,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'JP',
			'code_sta'   => 'FSM',
			'name_sta'   => 'Fukushima',
			'sort_order' => 306,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'JP',
			'code_sta'   => 'GFU',
			'name_sta'   => 'Gifu',
			'sort_order' => 307,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'JP',
			'code_sta'   => 'GUM',
			'name_sta'   => 'Gunma',
			'sort_order' => 308,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'JP',
			'code_sta'   => 'HRS',
			'name_sta'   => 'Hiroshima',
			'sort_order' => 309,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'JP',
			'code_sta'   => 'HKD',
			'name_sta'   => 'Hokkaido',
			'sort_order' => 310,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'JP',
			'code_sta'   => 'HYG',
			'name_sta'   => 'Hyogo',
			'sort_order' => 311,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'JP',
			'code_sta'   => 'IBR',
			'name_sta'   => 'Ibaraki',
			'sort_order' => 312,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'JP',
			'code_sta'   => 'IKW',
			'name_sta'   => 'Ishikawa',
			'sort_order' => 313,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'JP',
			'code_sta'   => 'IWT',
			'name_sta'   => 'Iwate',
			'sort_order' => 314,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'JP',
			'code_sta'   => 'KGW',
			'name_sta'   => 'Kagawa',
			'sort_order' => 315,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'JP',
			'code_sta'   => 'KGS',
			'name_sta'   => 'Kagoshima',
			'sort_order' => 316,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'JP',
			'code_sta'   => 'KNG',
			'name_sta'   => 'Kanagawa',
			'sort_order' => 317,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'JP',
			'code_sta'   => 'KCH',
			'name_sta'   => 'Kochi',
			'sort_order' => 318,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'JP',
			'code_sta'   => 'KMM',
			'name_sta'   => 'Kumamoto',
			'sort_order' => 319,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'JP',
			'code_sta'   => 'KYT',
			'name_sta'   => 'Kyoto',
			'sort_order' => 320,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'JP',
			'code_sta'   => 'MIE',
			'name_sta'   => 'Mie',
			'sort_order' => 321,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'JP',
			'code_sta'   => 'MYG',
			'name_sta'   => 'Miyagi',
			'sort_order' => 322,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'JP',
			'code_sta'   => 'MYZ',
			'name_sta'   => 'Miyazaki',
			'sort_order' => 323,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'JP',
			'code_sta'   => 'NGN',
			'name_sta'   => 'Nagano',
			'sort_order' => 324,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'JP',
			'code_sta'   => 'NGS',
			'name_sta'   => 'Nagasaki',
			'sort_order' => 325,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'JP',
			'code_sta'   => 'NRA',
			'name_sta'   => 'Nara',
			'sort_order' => 326,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'JP',
			'code_sta'   => 'NGT',
			'name_sta'   => 'Niigata',
			'sort_order' => 327,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'JP',
			'code_sta'   => 'OTA',
			'name_sta'   => 'Oita',
			'sort_order' => 328,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'JP',
			'code_sta'   => 'OKY',
			'name_sta'   => 'Okayama',
			'sort_order' => 329,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'JP',
			'code_sta'   => 'OKN',
			'name_sta'   => 'Okinawa',
			'sort_order' => 330,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'JP',
			'code_sta'   => 'OSK',
			'name_sta'   => 'Osaka',
			'sort_order' => 331,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'JP',
			'code_sta'   => 'SAG',
			'name_sta'   => 'Saga',
			'sort_order' => 332,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'JP',
			'code_sta'   => 'STM',
			'name_sta'   => 'Saitama',
			'sort_order' => 333,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'JP',
			'code_sta'   => 'SHG',
			'name_sta'   => 'Shiga',
			'sort_order' => 334,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'JP',
			'code_sta'   => 'SMN',
			'name_sta'   => 'Shimane',
			'sort_order' => 335,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'JP',
			'code_sta'   => 'SZK',
			'name_sta'   => 'Shizuoka',
			'sort_order' => 336,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'JP',
			'code_sta'   => 'TOC',
			'name_sta'   => 'Tochigi',

			'sort_order' => 337,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'JP',
			'code_sta'   => 'TKS',
			'name_sta'   => 'Tokushima',
			'sort_order' => 338,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'JP',
			'code_sta'   => 'TKY',
			'name_sta'   => 'Tokyo',
			'sort_order' => 335,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'JP',
			'code_sta'   => 'TTR',
			'name_sta'   => 'Tottori',
			'sort_order' => 336,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'JP',
			'code_sta'   => 'TYM',
			'name_sta'   => 'Toyama',
			'sort_order' => 337,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'JP',
			'code_sta'   => 'WKY',
			'name_sta'   => 'Wakayama',
			'sort_order' => 338,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'JP',
			'code_sta'   => 'YGT',
			'name_sta'   => 'Yamagata',
			'sort_order' => 339,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'JP',
			'code_sta'   => 'YGC',
			'name_sta'   => 'Yamaguchi',
			'sort_order' => 340,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'JP',
			'code_sta'   => 'YNS',
			'name_sta'   => 'Yamanashi',
			'sort_order' => 341,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'AR',
			'code_sta'   => 'C',
			'name_sta'   => 'Buenos Aires (Autonomous City)',
			'sort_order' => 342,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'AR',
			'code_sta'   => 'B',
			'name_sta'   => 'Buenos Aires Province',
			'sort_order' => 343,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'AR',
			'code_sta'   => 'K',
			'name_sta'   => 'Catamarca',
			'sort_order' => 344,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'AR',
			'code_sta'   => 'H',
			'name_sta'   => 'Chaco',
			'sort_order' => 345,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'AR',
			'code_sta'   => 'U',
			'name_sta'   => 'Chubut',
			'sort_order' => 346,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'AR',
			'code_sta'   => 'X',
			'name_sta'   => 'Córdoba',
			'sort_order' => 347,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'AR',
			'code_sta'   => 'W',
			'name_sta'   => 'Corrientes',
			'sort_order' => 348,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'AR',
			'code_sta'   => 'E',
			'name_sta'   => 'Entre Ríos',
			'sort_order' => 349,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'AR',
			'code_sta'   => 'P',
			'name_sta'   => 'Formosa',
			'sort_order' => 350,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'AR',
			'code_sta'   => 'Y',
			'name_sta'   => 'Jujuy',
			'sort_order' => 351,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'AR',
			'code_sta'   => 'L',
			'name_sta'   => 'La Pampa',
			'sort_order' => 352,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'AR',
			'code_sta'   => '',
			'name_sta'   => '',
			'sort_order' => 353,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'AR',
			'code_sta'   => 'F',
			'name_sta'   => 'La Rioja',
			'sort_order' => 354,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'AR',
			'code_sta'   => 'M',
			'name_sta'   => 'Mendoza',
			'sort_order' => 355,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'AR',
			'code_sta'   => 'N',
			'name_sta'   => 'Misiones',
			'sort_order' => 356,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'AR',
			'code_sta'   => 'Q',
			'name_sta'   => 'Neuquén',
			'sort_order' => 357,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'AR',
			'code_sta'   => 'R',
			'name_sta'   => 'Río Negro',
			'sort_order' => 358,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'AR',
			'code_sta'   => 'A',
			'name_sta'   => 'Salta',
			'sort_order' => 359,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'AR',
			'code_sta'   => 'J',
			'name_sta'   => 'San Juan',
			'sort_order' => 360,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'AR',
			'code_sta'   => 'D',
			'name_sta'   => 'San Luis',
			'sort_order' => 361,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'AR',
			'code_sta'   => 'Z',
			'name_sta'   => 'Santa Cruz',
			'sort_order' => 362,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'AR',
			'code_sta'   => 'S',
			'name_sta'   => 'Santa Fe',
			'sort_order' => 363,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'AR',
			'code_sta'   => 'G',
			'name_sta'   => 'Santiago del Estero',
			'sort_order' => 364,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'AR',
			'code_sta'   => 'V',
			'name_sta'   => 'Tierra del Fuego',
			'sort_order' => 365,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'AR',
			'code_sta'   => 'T',
			'name_sta'   => 'Tucumán',
			'sort_order' => 366,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'US',
			'code_sta'   => 'AA',
			'name_sta'   => 'Armed Forces of the Americas ',
			'sort_order' => 63,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'US',
			'code_sta'   => 'AE',
			'name_sta'   => 'Armed Forces of Europe',
			'sort_order' => 64,
			'group_sta'  => '',
		),
		array(
			'iso2_cnt'   => 'US',
			'code_sta'   => 'AP',
			'name_sta'   => 'Armed Forces of the Pacific',
			'sort_order' => 65,
			'group_sta'  => '',
		),
	),
);
